name: build

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.2'

    - name: Adblock
      run: |
        curl https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt --output adguard_ads.txt
        curl https://ublockorigin.github.io/uAssets/thirdparties/easylist.txt --output easylist.txt
        curl https://filters.adtidy.org/extension/ublock/filters/3.txt --output adguard_privacy.txt
        curl https://ublockorigin.github.io/uAssets/thirdparties/easyprivacy.txt --output easyprivacy.txt
        ruby script.rb
        
    - name: Commit and Push
      run: |
        git config --global user.name github-actions
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add adguard_ads.txt easylist.txt adguard_privacy.txt easyprivacy.txt
        git commit -m 'Auto Update' || exit 0
        git push
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
