name: build

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.3'
    - uses: actions/setup-node@v4
      with:
          node-version: latest
    - run: npm install @adguard/agtree

    - name: Adblock
      run: |
        gem install httparty
        ruby script.rb
        
    - name: Commit and Push
      run: |
        git config --global user.name github-actions
        git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
        rm -rf node_modules
        rm package.json package-lock.json filterlist.txt parsedfilter.json
        git add .
        git commit -m 'Auto Update' || exit 0
        git push

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 1
